### PR TITLE
Fix wrong upload params order for signing hash

### PR DESCRIPTION
**Pull request by viettranx**

### CODE REVIEW

**Comment by viettranx** [comment]
I've resolve an issue can not upload files due to wrong parameter order when signing hash.
By the way, the PR include my additional colors on response struct.

**Comment by viettranx** [comment]
[Fix bug wrong update parameters order for signing (Cloudinary)](https://trello.com/c/VrF3uTyv/70-fix-bug-wrong-update-parameters-order-for-signing-cloudinary)

**Comment by viettranx** [comment]
[Fix bug wrong update parameters order for signing (Cloudinary)](https://trello.com/c/VrF3uTyv/70-fix-bug-wrong-update-parameters-order-for-signing-cloudinary)

**Review by trangmaiq — APPROVED** [review]
Thank you @viettranx.

**Pull request merged**
